import type {NextPage} from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

import Layout from '../components/layout';


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta property="og:title" content="Create Next App" key="title" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>kienankb</h1>
      </header>
      <Layout>
        <div>foobar</div>
      </Layout>

      <footer>
      </footer>
    </div>
  )
}

export default Home
